In [1]:
import pandas as pd
import numpy as np
from time import sleep
import os.path

# Formando base com todos os autores

### Base contém título e resumo com 1, 2, 3 e all gramas, além do ID do autor. 
### Queremo a opção com 1 grama, e salvar cada conteúdo num arquivo txt diferente. A partir dai o script de Renato assume o mesmo pipeline utilizando nos demais trabalhos.

In [2]:
doc_ter_matrix = pd.read_csv('C:\\Users\\CoffeeLake_01\\Desktop\\ASOC-MGP\\arXiv\\NosRede_ARXIV-IA_GLOBAL.csv',
                  sep = ',')
doc_ter_matrix.shape

(372, 7)

In [3]:
doc_ter_matrix.head(5)

,Id,Label,document,gram2,gram3,allgrams,community
0,6474,6474,Learning;Belief;Networks;Domains;Recursively;E...,Learning Belief;Belief Networks;Networks Domai...,Learning Belief Networks;Belief Networks Domai...,Learning;Belief;Networks;Domains;Recursively;E...,6
1,8824,8824,Symbolic;Approach;Reasoning;Linguistic;Quantif...,Symbolic Approach;Approach Reasoning;Reasoning...,Symbolic Approach Reasoning;Approach Reasoning...,Symbolic;Approach;Reasoning;Linguistic;Quantif...,116
2,21014,21014,Efficient;Test;Selection;Active;Diagnosis;Entr...,Efficient Test;Test Selection;Selection Active...,Efficient Test Selection;Test Selection Active...,Efficient;Test;Selection;Active;Diagnosis;Entr...,151
3,21015,21015,Resourceful;Contextual;Bandits;study;contextua...,Resourceful Contextual;Contextual Bandits;Band...,Resourceful Contextual Bandits;Contextual Band...,Resourceful;Contextual;Bandits;study;contextua...,151
4,21016,21016,Learning;Performance;Prediction;Markets;Kelly;...,Learning Performance;Performance Prediction;Pr...,Learning Performance Prediction;Performance Pr...,Learning;Performance;Prediction;Markets;Kelly;...,151

In [4]:
doc_ter_matrix2 = doc_ter_matrix[['Id', 'document', 'community']]
doc_ter_matrix2.head(5)

      Id                                           document  community
0   6474  Learning;Belief;Networks;Domains;Recursively;E...          6
1   8824  Symbolic;Approach;Reasoning;Linguistic;Quantif...        116
2  21014  Efficient;Test;Selection;Active;Diagnosis;Entr...        151
3  21015  Resourceful;Contextual;Bandits;study;contextua...        151
4  21016  Learning;Performance;Prediction;Markets;Kelly;...        151

### Salvando cada conteúdo do artigo num .txt diferente, onde o nome do arquivo é o identificador do autor e sua comunidade.

In [5]:
identList = []
comList = []
for index, row in doc_ter_matrix2.iterrows():
    identificador, documento, comunidade  = row
    identList = [identList, identificador]
    nome = 'txt\\' + str(identificador) + '_' + str(comunidade) + '.txt'
    texto = documento.replace(";", " ")
    file = open(nome,"w+")
    file.write(texto)
    file.close()

# Pipeline Renato a partir dos arquivos .txt

In [6]:
import nltk
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import re

In [7]:
nltk.download('stopwords')
nltk.download('punkt')
stopwords = nltk.corpus.stopwords.words('english')
stemmer = SnowballStemmer("english")
def tokenize_and_stem(text):
    # first tokenize by sentence, then by word to ensure that punctuation is caught as it's own token
    tokens = [word for sent in nltk.sent_tokenize(re.sub('[-\xad][\s\n]','',text)) \
                          for word in nltk.word_tokenize(sent)]
    filtered_tokens = []
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if re.search('[a-zA-Z]{3,}', token):
            filtered_tokens.append(token)
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems
    #return filtered_tokens

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\CoffeeLake_01\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\CoffeeLake_01\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [8]:
tfidf_vectorizer = TfidfVectorizer(input='filename',max_df=0.95, max_features=20000,
                                 min_df=0.05, stop_words='english',
                                 use_idf=True, tokenizer=tokenize_and_stem, ngram_range=(1,3))
import glob
t = [f for f in glob.glob("txt/*.txt", recursive=False)]
#t = !ls txt2/*.txt
%time tfidf_matrix = tfidf_vectorizer.fit_transform(t)

print(tfidf_matrix.shape)

C:\Users\CoffeeLake_01\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:301: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'veri', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev', 'whi', 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

Wall time: 2.18 s
(372, 579)

In [9]:
terms = tfidf_vectorizer.get_feature_names()
terms[:10]

['abstract',
 'account',
 'accur',
 'accuraci',
 'achiev',
 'action',
 'activ',
 'acycl',
 'adapt',
 'addit']

In [10]:
with open('terms.txt','w') as f:
    f.write('\n'.join(terms))

In [11]:
x = tfidf_matrix.toarray()

In [12]:
df = pd.DataFrame(x,columns=terms,index=[re.sub('txt?/(\d+.?\d+v\d+)\.txt','\\1',a) for a in t])
df.head()

,abstract,account,accur,accuraci,achiev,action,activ,acycl,adapt,addit,...,varieti,various,version,view,weak,weight,well-known,wide,world,yield
txt\100194_116.txt,0.0,0.019533,0.0,0.0,0.0,0.0,0.0,0.0,0.018397,0.0,...,0.0,0.018021,0.0,0.088916,0.023061,0.058600,0.021141,0.0,0.035802,0.0
txt\100195_116.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.065500,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.069546,0.000000,0.0,0.000000,0.0
txt\100196_116.txt,0.0,0.021401,0.0,0.0,0.0,0.0,0.0,0.0,0.020156,0.0,...,0.0,0.019744,0.0,0.077933,0.025266,0.064202,0.023162,0.0,0.039225,0.0
txt\100197_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0
txt\100198_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0

In [13]:
df['comunidade'] = df.index
df[['id', 'comunidade']] = df['comunidade'].str.split("_", n = 1, expand = True)
df.head()

,abstract,account,accur,accuraci,achiev,action,activ,acycl,adapt,addit,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
txt\100194_116.txt,0.0,0.019533,0.0,0.0,0.0,0.0,0.0,0.0,0.018397,0.0,...,0.0,0.088916,0.023061,0.058600,0.021141,0.0,0.035802,0.0,116.txt,txt\100194
txt\100195_116.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.065500,0.0,...,0.0,0.000000,0.000000,0.069546,0.000000,0.0,0.000000,0.0,116.txt,txt\100195
txt\100196_116.txt,0.0,0.021401,0.0,0.0,0.0,0.0,0.0,0.0,0.020156,0.0,...,0.0,0.077933,0.025266,0.064202,0.023162,0.0,0.039225,0.0,116.txt,txt\100196
txt\100197_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0,256.txt,txt\100197
txt\100198_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0,256.txt,txt\100198

In [14]:
df['comunidade'] = df['comunidade'].str.replace('.txt', '')
df['id'] = df['id'].str.replace('txt', '')
df['id'] = df['id'].str.replace('\\', '')
df.head()

,abstract,account,accur,accuraci,achiev,action,activ,acycl,adapt,addit,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
txt\100194_116.txt,0.0,0.019533,0.0,0.0,0.0,0.0,0.0,0.0,0.018397,0.0,...,0.0,0.088916,0.023061,0.058600,0.021141,0.0,0.035802,0.0,116,100194
txt\100195_116.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.065500,0.0,...,0.0,0.000000,0.000000,0.069546,0.000000,0.0,0.000000,0.0,116,100195
txt\100196_116.txt,0.0,0.021401,0.0,0.0,0.0,0.0,0.0,0.0,0.020156,0.0,...,0.0,0.077933,0.025266,0.064202,0.023162,0.0,0.039225,0.0,116,100196
txt\100197_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0,256,100197
txt\100198_256.txt,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.125230,0.0,0.000000,0.0,256,100198

### Definindo base de dados sem medida de centralidade

In [15]:
autorWord_community = df.drop(['id','comunidade'],axis=1).\
                            replace(to_replace=0,value=np.NaN).\
                            apply(lambda a: pd.qcut(a,3,labels=['baixo','medio','alto']))
autorWord_community = autorWord_community.apply(lambda a: a.cat.add_categories(['zero']))
autorWord_community['comunidade'] = df.comunidade
autorWord_community['id'] = df.id
autorWord_community.head()

,abstract,account,accur,accuraci,achiev,action,activ,acycl,adapt,addit,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
txt\100194_116.txt,NaN,baixo,NaN,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,alto,baixo,medio,baixo,NaN,baixo,NaN,116,100194
txt\100195_116.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medio,NaN,...,NaN,NaN,NaN,medio,NaN,NaN,NaN,NaN,116,100195
txt\100196_116.txt,NaN,baixo,NaN,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,alto,baixo,medio,baixo,NaN,baixo,NaN,116,100196
txt\100197_256.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,alto,NaN,NaN,NaN,256,100197
txt\100198_256.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,alto,NaN,NaN,NaN,256,100198

In [16]:
autorWord_community.shape

(372, 581)

In [17]:
autorWord_community.comunidade.unique()

array(['116', '256', '104', '80', '151', '153', '6', '145', '134', '156'],
      dtype=object)

### Definindo base de dados COM medida de centralidade

In [18]:
nosRede_centralidade_grau = pd.read_csv('C:\\Users\\CoffeeLake_01\\Desktop\\ASOC-MGP\\arXiv\\NosRede_ARXIV-IA_GRAU.csv',
                  sep = ',')
nosRede_centralidade_grau.head(10)

      Id  Label  community
0   6474   6474          6
1   8824   8824        116
2  21014  21014        151
3  21015  21015        151
4  31089  31089        134
5  31116  31116         80
6  31136  31136        145
7  31137  31137        116
8  31138  31138        116
9  31151  31151        151

In [19]:
autorWord_community['id'] = autorWord_community.id.astype('int64', copy=False)
autorWord_community_c = pd.merge(nosRede_centralidade_grau, autorWord_community, left_on='Id', right_on='id')
autorWord_community_c.head(10)

,Id,Label,community,abstract,account,accur,accuraci,achiev,action,activ,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
0,6474,6474,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6474
1,8824,8824,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,medio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,8824
2,21014,21014,151,NaN,NaN,NaN,NaN,NaN,NaN,baixo,...,NaN,NaN,NaN,medio,NaN,medio,NaN,NaN,151,21014
3,21015,21015,151,NaN,NaN,NaN,baixo,alto,alto,NaN,...,NaN,NaN,NaN,baixo,NaN,medio,NaN,NaN,151,21015
4,31089,31089,134,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,medio,NaN,baixo,NaN,NaN,NaN,NaN,134,31089
5,31116,31116,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medio,80,31116
6,31136,31136,145,medio,NaN,NaN,baixo,alto,baixo,NaN,...,medio,NaN,NaN,NaN,baixo,NaN,baixo,NaN,145,31136
7,31137,31137,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,medio,NaN,NaN,NaN,NaN,baixo,NaN,116,31137
8,31138,31138,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,31138
9,31151,31151,151,NaN,baixo,baixo,baixo,baixo,NaN,baixo,...,NaN,NaN,NaN,medio,NaN,NaN,NaN,baixo,151,31151

In [20]:
autorWord_community_c.shape

(100, 584)

In [21]:
autorWord_community_c.comunidade.unique()

array(['6', '116', '151', '134', '80', '145', '156', '104', '153', '256'],
      dtype=object)

### Salvando bases em arquivos

In [22]:
autorWord_community.head(10)

,abstract,account,accur,accuraci,achiev,action,activ,acycl,adapt,addit,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
txt\100194_116.txt,NaN,baixo,NaN,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,alto,baixo,medio,baixo,NaN,baixo,NaN,116,100194
txt\100195_116.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medio,NaN,...,NaN,NaN,NaN,medio,NaN,NaN,NaN,NaN,116,100195
txt\100196_116.txt,NaN,baixo,NaN,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,alto,baixo,medio,baixo,NaN,baixo,NaN,116,100196
txt\100197_256.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,alto,NaN,NaN,NaN,256,100197
txt\100198_256.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,alto,NaN,NaN,NaN,256,100198
txt\100199_104.txt,NaN,alto,NaN,baixo,alto,NaN,NaN,NaN,medio,alto,...,baixo,NaN,NaN,baixo,medio,medio,medio,NaN,104,100199
txt\100200_80.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medio,medio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,100200
txt\100204_151.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151,100204
txt\100219_153.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153,100219
txt\100220_153.txt,NaN,medio,medio,medio,NaN,baixo,alto,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153,100220

In [23]:
autorWord_community_c.head(10)

,Id,Label,community,abstract,account,accur,accuraci,achiev,action,activ,...,version,view,weak,weight,well-known,wide,world,yield,comunidade,id
0,6474,6474,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6474
1,8824,8824,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,medio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,8824
2,21014,21014,151,NaN,NaN,NaN,NaN,NaN,NaN,baixo,...,NaN,NaN,NaN,medio,NaN,medio,NaN,NaN,151,21014
3,21015,21015,151,NaN,NaN,NaN,baixo,alto,alto,NaN,...,NaN,NaN,NaN,baixo,NaN,medio,NaN,NaN,151,21015
4,31089,31089,134,NaN,NaN,NaN,NaN,NaN,baixo,NaN,...,NaN,medio,NaN,baixo,NaN,NaN,NaN,NaN,134,31089
5,31116,31116,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medio,80,31116
6,31136,31136,145,medio,NaN,NaN,baixo,alto,baixo,NaN,...,medio,NaN,NaN,NaN,baixo,NaN,baixo,NaN,145,31136
7,31137,31137,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,medio,NaN,NaN,NaN,NaN,baixo,NaN,116,31137
8,31138,31138,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,31138
9,31151,31151,151,NaN,baixo,baixo,baixo,baixo,NaN,baixo,...,NaN,NaN,NaN,medio,NaN,NaN,NaN,baixo,151,31151

In [24]:
autorWord_community = autorWord_community.drop(['id'], axis = 1)
autorWord_community.fillna('zero').to_csv('arXiv_resumoTitulo.csv', sep=',', index=False)

In [25]:
autorWord_community_c = autorWord_community_c.drop(['Id','Label','community','id'], axis = 1)
autorWord_community_c.fillna('zero').to_csv('arXiv_resumoTitulo_centralidadeGrau.csv', sep=',', index=False)